"""Probe runner: execute a ProbeSchedule against a live server, emit a §2 bundle.

Thin live layer (not behavior-tested). Assumes a healthy OpenAI-compatible
endpoint (the orchestrator's ``server_lifecycle.sh`` owns server launch/shutdown).

Architecture: traffic is generated by the vendored ``benchmark_serving.py`` (via
``bench_driver``), which emits per-request epoch ``request_timestamps`` + ttft +
itl. The extended nvidia-smi power log and the /metrics engine log run
**continuously** across the whole schedule (one ``power.csv`` + one ``engine.csv``,
all epoch-stamped). The manifest records, per level, the **absolute epoch window**
``[t_start, t_end]`` so every power/engine sample maps to a level and every request
maps to an absolute time — that triple (requests ↔ engine ↔ power, all in epoch
seconds) is the full alignment contract.

One bundle per schedule. Pure helpers (``build_level_window``,
``assemble_requests_json``) are unit-testable; ``run`` is the live orchestration.
"""

from __future__ import annotations

import json
import subprocess
import sys
import threading
import time
from contextlib import contextmanager
from pathlib import Path

_CLIENT = Path(__file__).resolve().parents[1] / "client"
sys.path.insert(0, str(_CLIENT))

import bench_driver  # noqa: E402


def _client_mod(name):
    from importlib import import_module
    return import_module(name)


@contextmanager
def logging_session(run_dir, base_url):
    """Run the continuous power + /metrics loggers for the duration; yield clock.

    Shared by the probe runner and the agentic session runner so both bundles get
    one epoch-stamped power.csv + engine.csv.
    """
    power_logger = _client_mod("power_logger")
    metrics_logger = _client_mod("metrics_logger")
    run_manifest = _client_mod("run_manifest")

    run_dir = Path(run_dir)
    pf = open(run_dir / "power.csv", "w")
    power_proc = subprocess.Popen(
        power_logger.nvidia_smi_command(), stdout=pf, stderr=subprocess.DEVNULL)
    clock = run_manifest.capture_clock()
    stop = threading.Event()

    def _engine_thread():
        import asyncio
        asyncio.run(metrics_logger.poll_loop(
            base_url, str(run_dir / "engine.csv"), 0.25, stop))

    engine_t = threading.Thread(target=_engine_thread, daemon=True)
    engine_t.start()
    try:
        yield clock
    finally:
        stop.set()
        engine_t.join(timeout=10)
        power_proc.terminate()
        pf.close()


def build_level_window(level, t_start_epoch, t_end_epoch, command, summary) -> dict:
    """Manifest entry locating a level in absolute time (pure)."""
    return {
        "level": level.level,
        "label": level.label,
        "concurrency": level.concurrency,
        "num_prompts": level.num_prompts,
        "t_start_epoch": float(t_start_epoch),
        "t_end_epoch": float(t_end_epoch),
        "params": {"input_len": level.request.input_len,
                   "output_len": level.request.output_len,
                   "prefix_len": level.request.prefix_len,
                   "ignore_eos": level.request.ignore_eos},
        "command": command,      # exact benchmark invocation (reproducibility)
        "summary": summary,      # per-level throughput aggregates
    }


def assemble_requests_json(level_results) -> dict:
    """Merge per-level per-request arrays into the requests.json dict (pure)."""
    return bench_driver.merge_request_arrays(level_results)


def run(schedule, *, model, hardware, tp, gpus_per_node, server_cfg,
        out_root, base_url="http://localhost:8000/v1",
        weight_footprint_bytes=None, dtype_hint=None, n_active_override=None,
        run_id=None):
    """Execute ``schedule`` and write the bundle. Returns the run directory."""
    run_manifest = _client_mod("run_manifest")
    arch_extract = _client_mod("arch_extract")

    run_id = run_id or f"{hardware.lower()}_{schedule.probe_type}_tp{tp}_{int(time.time())}"
    run_dir = Path(out_root) / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    levels_dir = run_dir / "levels"
    levels_dir.mkdir(exist_ok=True)

    arch = arch_extract.extract_arch(
        arch_extract.load_config(model), dtype_hint=dtype_hint,
        weight_footprint_bytes=weight_footprint_bytes,
        n_active_override=n_active_override,
    )

    # --- drive levels under the continuous loggers -----------------------
    window_start = time.time()
    level_results, level_windows = [], []
    with logging_session(run_dir, base_url) as clock:
        for lvl in schedule.levels:
            result_path = levels_dir / f"level_{lvl.level:03d}.json"
            command = (None if lvl.concurrency <= 0
                       else bench_driver.build_command(model, base_url, tp, lvl, result_path))
            t0 = time.time()
            result = bench_driver.run_level(model, base_url, tp, lvl, result_path)
            t1 = time.time()
            level_results.append(result)
            level_windows.append(
                build_level_window(lvl, t0, t1, command, result["summary"]))
    window_end = time.time()

    # --- write requests.json + manifest ----------------------------------
    requests = assemble_requests_json(level_results)
    (run_dir / "requests.json").write_text(json.dumps(requests))

    manifest = run_manifest.build_manifest(
        run_id=run_id,
        probe={"type": schedule.probe_type,
               "window": {"start_epoch": window_start, "end_epoch": window_end},
               "levels": level_windows},
        model=model, arch=arch, hardware=hardware, tp=tp,
        gpus_per_node=gpus_per_node,
        server=dict(server_cfg, **schedule.server_overrides),
        versions=run_manifest.collect_versions(),
        clock=clock,
    )
    run_manifest.write_manifest(str(run_dir / "manifest.json"), manifest)
    return run_dir
