_wandb:
    value:
        cli_version: 0.22.2
        e:
            6sy8a0yj3a8plfx8fq9cf23dpx9pwc7m:
                args:
                    - --data_file
                    - ./training_data/vllm-benchmark_llama-3-8b_a100.npz
                    - --tp
                    - "1"
                    - --hardware_accelerator
                    - a100
                    - --model
                    - llama-3-8b
                    - --lr
                    - "1e-4"
                codePath: model/train_entry.py
                codePathLocal: train_entry.py
                cpu_count: 96
                cpu_count_logical: 96
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1065418129408"
                        used: "67485786112"
                email: grant.wilkins371@gmail.com
                executable: /home/azureuser/miniconda3/envs/inference/bin/python3
                git:
                    commit: 25a588620ad3ebcc2f40281c7f16b7c22300a770
                    remote: https://github.com/grantwilkins/powertrace-sim.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-786afb41-2e98-1c31-1fa0-fd70730a0a2c
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-834e2131-941a-5c1e-8b66-790193996356
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-f0434b5c-93cd-c772-cb3b-24520aa08711
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-3377cb76-0746-76fe-9c1a-6178453b84d5
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-e8c3dc2a-9603-d830-352b-c97be9fbe946
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-0638da5d-b846-081d-75eb-4e97cb647429
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-573eb394-8fc7-4f1f-80b1-c794a645a6d8
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-d1d05e66-5b6a-e3d8-4974-1de322f34ec0
                host: gpu-vmss000001
                memory:
                    total: "1902335221760"
                os: Linux-5.15.0-1089-azure-x86_64-with-glibc2.31
                program: /home/azureuser/powertrace-sim/model/train_entry.py
                python: CPython 3.12.0
                root: /home/azureuser/powertrace-sim/model
                startedAt: "2025-10-29T05:10:57.897480Z"
                writerId: 6sy8a0yj3a8plfx8fq9cf23dpx9pwc7m
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 1
                - 16
            "4": 3.12.0
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
device:
    value: cuda
hidden_size:
    value: 64
input_dim:
    value: 6
lr:
    value: 0.0001
num_epochs:
    value: 500
num_states:
    value: 6
tp:
    value: 1
train_samples:
    value: 24
val_samples:
    value: 6
